List<Map<String, Object>> pwdData = [
    {
      'name': 'Jerry', 
      'age': '15', 
      'disability': 'Cerebral Palsy',
      'image': 'assets/image/person1.jpeg',
      'location': 'Yishun',
      'about': 'I enjoy being out and about. Passionate about yoga and mindfulness. Love music, traveling and hanging out.',
      'like': '\u{2022} Walks at the park\n\u{2022} Walks on the water',
      'dislike': '\u{2022} No Walks at the park\n\u{2022} No walks on the water',
      'comm': 'Watch my eyes\n\u{2022} No - Look Up\n\u{2022} Yes - Look Down/Nod Slightly\n\u{2022} Don\'t Know - Look Sideways',
    },{
      'name': 'Tom', 
      'age': '18', 
      'disability': 'Epilepsy',
      'image': 'assets/image/person2.jpeg',
      'location': 'Tampines',
      'about': 'I enjoy being in and around. Passionate about coffee and tea. Love music, walks in the park and hanging out.',
      'like': '\u{2022} Walks at the park\n\u{2022} Walks on the water',
      'dislike': '\u{2022} No Walks at the park\n\u{2022} No walks on the water',
      'comm': 'Watch my eyes\n\u{2022} No - Look Up\n\u{2022} Yes - Look Down/Nod Slightly\n\u{2022} Don\'t Know - Look Sideways',
    },{
      'name': 'Sabrina', 
      'age': '16', 
      'disability': 'Blind',
      'image': 'assets/image/person3.jpeg',
      'location': 'Bedok',
      'about': 'Love music, walks in the park and hanging out.',
      'like': '\u{2022} Walks at the park\n\u{2022} Walks on the water',
      'dislike': '\u{2022} No Walks at the park\n\u{2022} No walks on the water',
      'comm': 'Watch my eyes\n\u{2022} No - Look Up\n\u{2022} Yes - Look Down/Nod Slightly\n\u{2022} Don\'t Know - Look Sideways',
    },{
      'name': 'Ray', 
      'age': '11', 
      'disability': 'Deaf',
      'image': 'assets/image/person4.jpeg',
      'location': 'SengKang',
      'about': 'Passionate about coffee and tea. Love music, walks in the park and hanging out.',
      'like': '\u{2022} Walks at the park\n\u{2022} Walks on the water',
      'dislike': '\u{2022} No Walks at the park\n\u{2022} No walks on the water',
      'comm': 'Watch my eyes\n\u{2022} No - Look Up\n\u{2022} Yes - Look Down/Nod Slightly\n\u{2022} Don\'t Know - Look Sideways',
    },{
      'name': 'Viknesh', 
      'age': '13', 
      'disability': 'ALS',
      'location': 'Bugis',
      'image': 'assets/image/person5.jpeg',
      'about': 'Love music, walks in the park and hanging out. I enjoy being in and around. Passionate about coffee and tea.',
      'like': '\u{2022} Walks at the park\n\u{2022} Walks on the water',
      'dislike': '\u{2022} No Walks at the park\n\u{2022} No walks on the water',
      'comm': 'Watch my eyes\n\u{2022} No - Look Up\n\u{2022} Yes - Look Down/Nod Slightly\n\u{2022} Don\'t Know - Look Sideways',
    },
  ];